name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: install deps
        run: npm ci
      - name: build
        run: CI=true npm run build
      - name: lint
        run: npm run test:lint
      - name: test
        run: CI=true npm test
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test the license scan action
    steps:
      - name: Hello world action step
        id: hello
        uses: lauravuo/licence-scan-js@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"